on: pull_request

name: Android CI

jobs:
  xpeho_workflows_android:
    uses: XPEHO/Xpeho-Workflows/.github/workflows/android.yaml@feat/ci
    with:
      JAVA_VERSION: '17'
    secrets:
      GOOGLE_SERVICE: ${{ secrets.GOOGLE_SERVICE_FILE }}