name: Build debug appbundle

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  releaseAppBundle:
    name: Build debug appbundle
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: xpeapp_android
    steps:
      - uses: actions/checkout@v4
      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'
          cache: gradle

      - name: Create firebase config file
        run: |
          echo "${{ secrets.GOOGLE_SERVICE_FILE }}" | base64 -d > app/google-services.json
          if [ -n "${{ secrets.UAT_CONFIG_FILE }}" ]; then
            mkdir -p app/config
            echo "${{ secrets.UAT_CONFIG_FILE }}" | base64 -d > app/config/uat.properties
          fi
         
      - name: Grant execute permission for gradlew and build
        run: |
          chmod +x ./gradlew
          ./gradlew bundleDebug

      - name: Upload appbundle artifact
        uses: actions/upload-artifact@v4
        with:
          name: debug-bundle
          path: "xpeapp_android/app/build/outputs/bundle/debug/app-debug.aab"

